### ISSUE TITLE
Formula mismatch CHEBI:41981

### ISSUE THREAD

**Issue by theArsalanM** [chembl/libRDChEBI#5]
CHEBI:41981 has formula "D2O" in ChEBI1.0, but in ChEBI2.0 it is being calculated as "H2O"

Note: _both ChEMBL and PubChem also report it as H2O_

Need to investigate if this is a bug or expected behavior.

**Comment by eloyfelix** [comment]
isotopes are not taken into account for now (we don't do it in ChEMBL) but we may want to do it in ChEBI.
Hydrogen is a bit special since Deuterium and Tritium are sometimes treated by replacing the [2H] and [3H] by D and T.

**Comment by eloyfelix** [comment]
this has been fixed
